// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Hex below is the result of `WorldResourceIdLib.encode({ namespace: "king", name: "ACLobbyStatus", typeId: RESOURCE_TABLE });`
ResourceId constant _tableId = ResourceId.wrap(0x74626b696e670000000000000000000041434c6f626279537461747573000000);
ResourceId constant ACLobbyStatusTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x00a1060020202020200100000000000000000000000000000000000000000000
);

struct ACLobbyStatusData {
  uint256 startTime;
  uint256 teamATotalTime;
  uint256 teamBTotalTime;
  uint256 teamAPlayers;
  uint256 teamBPlayers;
  bool claimed;
}

library ACLobbyStatus {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.UINT256;
    _keySchema[1] = SchemaType.UINT256;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](6);
    _valueSchema[0] = SchemaType.UINT256;
    _valueSchema[1] = SchemaType.UINT256;
    _valueSchema[2] = SchemaType.UINT256;
    _valueSchema[3] = SchemaType.UINT256;
    _valueSchema[4] = SchemaType.UINT256;
    _valueSchema[5] = SchemaType.BOOL;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "smartObjectId";
    keyNames[1] = "lastResetTime";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](6);
    fieldNames[0] = "startTime";
    fieldNames[1] = "teamATotalTime";
    fieldNames[2] = "teamBTotalTime";
    fieldNames[3] = "teamAPlayers";
    fieldNames[4] = "teamBPlayers";
    fieldNames[5] = "claimed";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get startTime.
   */
  function getStartTime(uint256 smartObjectId, uint256 lastResetTime) internal view returns (uint256 startTime) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get startTime.
   */
  function _getStartTime(uint256 smartObjectId, uint256 lastResetTime) internal view returns (uint256 startTime) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set startTime.
   */
  function setStartTime(uint256 smartObjectId, uint256 lastResetTime, uint256 startTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((startTime)), _fieldLayout);
  }

  /**
   * @notice Set startTime.
   */
  function _setStartTime(uint256 smartObjectId, uint256 lastResetTime, uint256 startTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((startTime)), _fieldLayout);
  }

  /**
   * @notice Get teamATotalTime.
   */
  function getTeamATotalTime(
    uint256 smartObjectId,
    uint256 lastResetTime
  ) internal view returns (uint256 teamATotalTime) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get teamATotalTime.
   */
  function _getTeamATotalTime(
    uint256 smartObjectId,
    uint256 lastResetTime
  ) internal view returns (uint256 teamATotalTime) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set teamATotalTime.
   */
  function setTeamATotalTime(uint256 smartObjectId, uint256 lastResetTime, uint256 teamATotalTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((teamATotalTime)), _fieldLayout);
  }

  /**
   * @notice Set teamATotalTime.
   */
  function _setTeamATotalTime(uint256 smartObjectId, uint256 lastResetTime, uint256 teamATotalTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((teamATotalTime)), _fieldLayout);
  }

  /**
   * @notice Get teamBTotalTime.
   */
  function getTeamBTotalTime(
    uint256 smartObjectId,
    uint256 lastResetTime
  ) internal view returns (uint256 teamBTotalTime) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get teamBTotalTime.
   */
  function _getTeamBTotalTime(
    uint256 smartObjectId,
    uint256 lastResetTime
  ) internal view returns (uint256 teamBTotalTime) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set teamBTotalTime.
   */
  function setTeamBTotalTime(uint256 smartObjectId, uint256 lastResetTime, uint256 teamBTotalTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((teamBTotalTime)), _fieldLayout);
  }

  /**
   * @notice Set teamBTotalTime.
   */
  function _setTeamBTotalTime(uint256 smartObjectId, uint256 lastResetTime, uint256 teamBTotalTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((teamBTotalTime)), _fieldLayout);
  }

  /**
   * @notice Get teamAPlayers.
   */
  function getTeamAPlayers(uint256 smartObjectId, uint256 lastResetTime) internal view returns (uint256 teamAPlayers) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get teamAPlayers.
   */
  function _getTeamAPlayers(uint256 smartObjectId, uint256 lastResetTime) internal view returns (uint256 teamAPlayers) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set teamAPlayers.
   */
  function setTeamAPlayers(uint256 smartObjectId, uint256 lastResetTime, uint256 teamAPlayers) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((teamAPlayers)), _fieldLayout);
  }

  /**
   * @notice Set teamAPlayers.
   */
  function _setTeamAPlayers(uint256 smartObjectId, uint256 lastResetTime, uint256 teamAPlayers) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((teamAPlayers)), _fieldLayout);
  }

  /**
   * @notice Get teamBPlayers.
   */
  function getTeamBPlayers(uint256 smartObjectId, uint256 lastResetTime) internal view returns (uint256 teamBPlayers) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get teamBPlayers.
   */
  function _getTeamBPlayers(uint256 smartObjectId, uint256 lastResetTime) internal view returns (uint256 teamBPlayers) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set teamBPlayers.
   */
  function setTeamBPlayers(uint256 smartObjectId, uint256 lastResetTime, uint256 teamBPlayers) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((teamBPlayers)), _fieldLayout);
  }

  /**
   * @notice Set teamBPlayers.
   */
  function _setTeamBPlayers(uint256 smartObjectId, uint256 lastResetTime, uint256 teamBPlayers) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((teamBPlayers)), _fieldLayout);
  }

  /**
   * @notice Get claimed.
   */
  function getClaimed(uint256 smartObjectId, uint256 lastResetTime) internal view returns (bool claimed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get claimed.
   */
  function _getClaimed(uint256 smartObjectId, uint256 lastResetTime) internal view returns (bool claimed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set claimed.
   */
  function setClaimed(uint256 smartObjectId, uint256 lastResetTime, bool claimed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((claimed)), _fieldLayout);
  }

  /**
   * @notice Set claimed.
   */
  function _setClaimed(uint256 smartObjectId, uint256 lastResetTime, bool claimed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((claimed)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(uint256 smartObjectId, uint256 lastResetTime) internal view returns (ACLobbyStatusData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint256 smartObjectId, uint256 lastResetTime) internal view returns (ACLobbyStatusData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 smartObjectId,
    uint256 lastResetTime,
    uint256 startTime,
    uint256 teamATotalTime,
    uint256 teamBTotalTime,
    uint256 teamAPlayers,
    uint256 teamBPlayers,
    bool claimed
  ) internal {
    bytes memory _staticData = encodeStatic(
      startTime,
      teamATotalTime,
      teamBTotalTime,
      teamAPlayers,
      teamBPlayers,
      claimed
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 smartObjectId,
    uint256 lastResetTime,
    uint256 startTime,
    uint256 teamATotalTime,
    uint256 teamBTotalTime,
    uint256 teamAPlayers,
    uint256 teamBPlayers,
    bool claimed
  ) internal {
    bytes memory _staticData = encodeStatic(
      startTime,
      teamATotalTime,
      teamBTotalTime,
      teamAPlayers,
      teamBPlayers,
      claimed
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 smartObjectId, uint256 lastResetTime, ACLobbyStatusData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.startTime,
      _table.teamATotalTime,
      _table.teamBTotalTime,
      _table.teamAPlayers,
      _table.teamBPlayers,
      _table.claimed
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 smartObjectId, uint256 lastResetTime, ACLobbyStatusData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.startTime,
      _table.teamATotalTime,
      _table.teamBTotalTime,
      _table.teamAPlayers,
      _table.teamBPlayers,
      _table.claimed
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256 startTime,
      uint256 teamATotalTime,
      uint256 teamBTotalTime,
      uint256 teamAPlayers,
      uint256 teamBPlayers,
      bool claimed
    )
  {
    startTime = (uint256(Bytes.slice32(_blob, 0)));

    teamATotalTime = (uint256(Bytes.slice32(_blob, 32)));

    teamBTotalTime = (uint256(Bytes.slice32(_blob, 64)));

    teamAPlayers = (uint256(Bytes.slice32(_blob, 96)));

    teamBPlayers = (uint256(Bytes.slice32(_blob, 128)));

    claimed = (_toBool(uint8(Bytes.slice1(_blob, 160))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    PackedCounter,
    bytes memory
  ) internal pure returns (ACLobbyStatusData memory _table) {
    (
      _table.startTime,
      _table.teamATotalTime,
      _table.teamBTotalTime,
      _table.teamAPlayers,
      _table.teamBPlayers,
      _table.claimed
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 smartObjectId, uint256 lastResetTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 smartObjectId, uint256 lastResetTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 startTime,
    uint256 teamATotalTime,
    uint256 teamBTotalTime,
    uint256 teamAPlayers,
    uint256 teamBPlayers,
    bool claimed
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(startTime, teamATotalTime, teamBTotalTime, teamAPlayers, teamBPlayers, claimed);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 startTime,
    uint256 teamATotalTime,
    uint256 teamBTotalTime,
    uint256 teamAPlayers,
    uint256 teamBPlayers,
    bool claimed
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(
      startTime,
      teamATotalTime,
      teamBTotalTime,
      teamAPlayers,
      teamBPlayers,
      claimed
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 smartObjectId, uint256 lastResetTime) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(lastResetTime));

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
