// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { KingOfTheHillConfig, KingOfTheHillConfigData, KingOfTheHillConfigTableId } from "./tables/KingOfTheHillConfig.sol";
import { KingOfTheHillStatus, KingOfTheHillStatusData, KingOfTheHillStatusTableId } from "./tables/KingOfTheHillStatus.sol";
