// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAreaControlLobby
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAreaControlLobby {
  function action__setLobbyConfig(
    uint256 _smartObjectId,
    uint256 _duration,
    uint256 _playerCount,
    uint256 _expectedItemId,
    uint256 _expectedItemQuantity
  ) external;

  function action__acResetGame(uint256 _smartObjectId) external;

  function action__acJoinGame(uint256 _smartObjectId, uint256 _team) external;

  function action__acStartGame(uint256 _smartObjectId) external;

  function action__acClaimPrize(uint256 _smartObjectId) external;
}
